analyzer:
  exclude:
    - build/**
    - ios/**
    - macos/**
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_initializing_formals: true
    use_primary_constructors: true
    use_declaring_parameters: true
    empty_container_bodies: true
    initialize_in_field_declaration: true
    unnecessary_const_in_enum_constructor: true
    unnecessary_primary_constructor_body: true
    unnecessary_type_name_in_constructor: true
    use_key_in_widget_constructors: false
